# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    sudo apt-get install -y nodejs
    node -v
    npm -v
  displayName: 'Install Node.js 14.x'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
    
- script: ls -R .nuxt
  displayName: 'List .nuxt directory contents'

- task: CopyFiles@2
  inputs:
    contents: '.nuxt/**'
    targetFolder: $(Build.ArtifactStagingDirectory)/.nuxt

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)/.nuxt
    artifactName: 'nuxt-build'

- script: ls -R $(Build.ArtifactStagingDirectory)
  displayName: 'List files in artifact staging directory'
  
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: false